<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_dashboard_graficos  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


// dashboatd snippets function
function event_Dashboard_Graficos_snippet( &$header )
{
	$header = "Quantidade de Tarefas";

$res = DB::query("select count(lista_id) as qtde FROM tb_lista_atividades");
$data = $res->fetchAssoc();
$res = "<div class='info-box'>";
//$res.= "<span class='info-img img_bgcolor_red glyphicon glyphicon-shopping-cart'></span>";
$res.= "<span class='info-img img_bgcolor_blue glyphicon glyphicon-tags'></span>";
$res.= "<div class='dashtext'>";
$res.= "Listas: ";
$res.= "<b>" . $data["qtde"] . "</b>";
$res.= "</div>";
$res.= "</div>";
echo $res;

;
}
function event_Dashboard_Graficos_snippet1( &$header )
{
	$header = "Quantidade de Tarefas";

$res = DB::query("select count(ativ_id) as qtde FROM tb_atividade");
$data = $res->fetchAssoc();
$res = "<div class='info-box'>";
//$res.= "<span class='info-img img_bgcolor_red glyphicon glyphicon-shopping-cart'></span>";
$res.= "<span class='info-img img_bgcolor_red glyphicon glyphicon-tags'></span>";
$res.= "<div class='dashtext'>";
$res.= "Tarefas: ";
$res.= "<b>" . $data["qtde"] . "</b>";
$res.= "</div>";
$res.= "</div>";
echo $res;

;
}
function event_Dashboard_Graficos_snippet2( &$header )
{
	// Query de teste e para buscar ultimos 30 dias na tabela de atividades
$query = "select datetime('now','localtime'), datetime('now','-30 day','localtime')";
$query = "select count(*) as qtde from tb_atividade where ativ_dt_ini >= datetime('now','-30 day','localtime')";
//echo $query; //Debug
// Qtde de Tarefas iniciadas nos últimos 30 dias (ativ_dt_ini >= now()-30days???)
$header = "Tarefas Iniciadas nos últimos 30 dias";

$res = DB::query($query);
$data = $res->fetchAssoc();
//print_r($data); //Debug
$res = "<div class='info-box'>";
//$res.= "<span class='info-img img_bgcolor_red glyphicon glyphicon-shopping-cart'></span>";
$res.= "<span class='info-img img_bgcolor_green glyphicon glyphicon-share'></span>";
$res.= "<div class='dashtext'>";
$res.= "Iniciadas: ";
$res.= "<b>" . $data["qtde"] . "</b>";
$res.= "</div>";
$res.= "</div>";
echo $res;

;
}
function event_Dashboard_Graficos_snippet3( &$header )
{
	// Query de teste e para buscar ultimos 30 dias na tabela de atividades
$query = "select datetime('now','localtime'), datetime('now','-30 day','localtime')";
$query = "select count(*) as qtde from tb_atividade where ativ_dt_fim >= datetime('now','-30 day','localtime')";
//echo $query; //Debug
// Qtde de Tarefas iniciadas nos últimos 30 dias (ativ_dt_ini >= now()-30days???)
$header = "Tarefas Encerradas nos últimos 30 dias";

$res = DB::query($query);
$data = $res->fetchAssoc();
//print_r($data); //Debug
$res = "<div class='info-box'>";
//$res.= "<span class='info-img img_bgcolor_red glyphicon glyphicon-shopping-cart'></span>";
$res.= "<span class='info-img img_bgcolor_blue glyphicon glyphicon-check'></span>";
$res.= "<div class='dashtext'>";
$res.= "Encerradas: ";
$res.= "<b>" . $data["qtde"] . "</b>";
$res.= "</div>";
$res.= "</div>";
echo $res;;
}

}
?>
