<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_dashboard_lista_e_tarefas  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


// dashboatd snippets function
function event_Dashboard_Lista_e_Tarefas_snippet( &$header )
{
	$header = "Quantidade de Tarefas";

$res = DB::query("select count(ativ_id) as qtde FROM tb_atividade");
$data = $res->fetchAssoc();
$res = "<div class='info-box'>";
//$res.= "<span class='info-img img_bgcolor_red glyphicon glyphicon-shopping-cart'></span>";
$res.= "<span class='info-img img_bgcolor_red glyphicon glyphicon-tags'></span>";
$res.= "<div class='dashtext'>";
$res.= "Tarefas: ";
$res.= "<b>" . $data["qtde"] . "</b>";
$res.= "</div>";
$res.= "</div>";
echo $res;

;
}
function event_Dashboard_Lista_e_Tarefas_snippet1( &$header )
{
	$header = "Quantidade de Tarefas";

$res = DB::query("select count(lista_id) as qtde FROM tb_lista_atividades");
$data = $res->fetchAssoc();
$res = "<div class='info-box'>";
//$res.= "<span class='info-img img_bgcolor_red glyphicon glyphicon-shopping-cart'></span>";
$res.= "<span class='info-img img_bgcolor_blue glyphicon glyphicon-tags'></span>";
$res.= "<div class='dashtext'>";
$res.= "Listas: ";
$res.= "<b>" . $data["qtde"] . "</b>";
$res.= "</div>";
$res.= "</div>";
echo $res;

;
}

}
?>
