<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_tb_categorias  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeDelete"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeEdit"]=true;

		$this->events["GetTablePermissions"]=true;


		$this->events["IsRecordEditable"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record deleted
function BeforeDelete($where, &$deleted_values, &$message, &$pageObject)
{

		
// Rene: Elimina os registros de uma categoria na tabela de associacao "tb_categorias_x_atividades"
global $dal;  // Tem que ser este nome, se mudar o nome, ex: $wl_dal_DataAccessLayer, gera o erro abaixo
//Fatal error: Call to a member function Table() on a non-object in C:\UwAmp\www\GTD_PHPRunner\output\include\tb_categorias_events.php on line 45
$wl_tb_categorias_x_atividades = $dal->Table("tb_categorias_x_atividades");
$wl_tb_categorias_x_atividades->Param["cate_id"] = $deleted_values["cate_id"];
$wl_tb_categorias_x_atividades->Delete();


// Rene: (opcional) Veriica se o registro foi excluido ou se ainda existe
$rs = DB::Query("select * from tb_categorias_x_atividades where cate_id = " . $deleted_values["cate_id"]);
$data=$rs->fetchAssoc();
if($data)
{
	// if record exists do something
	return false;
}
else
{
	// if dont exist do something else
	return true;
}
return true;

;		
} // function BeforeDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		

// Rene: Guarda dados de log antes de incluir ou alterar um registro
fctConfigura_Usuario($values['inclu_login'], $values['inclu_dt']);

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, &$pageObject)
{

		
// Rene: Guarda dados de log antes de incluir ou alterar um registro
fctConfigura_Usuario($values['alter_login'], $values['alter_dt']);

return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Get Table Permissions
function GetTablePermissions($permissions)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

// RENE: Teste de permissões. Nao consegui fazer funcionar o DELETE em Categorias
// $permissions = "AEDSP";

return $permissions;
;		
} // function GetTablePermissions

		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Is Record Editable
function IsRecordEditable($values, $isEditable)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

// Rene: Habilita o DELETE e exibe o ícone Edit no Grid (para paginas que exibem somente os dados do proprio cliente!)
$isEditable = true;

return $isEditable;
;		
} // function IsRecordEditable

		
		
		
		
		
		
		



}
?>
